# Generated by Django 3.1.1 on 2020-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='head_text',
            new_name='headline_text',
        ),
        migrations.AlterField(
            model_name='headline',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
